from setuptools import setup, find_packages


setup(
    name='nefertiti',
    version='0.0.3',
    description='personal common toolkit',
    author='sunxianliang',
    author_email='sunxianliang.cn@gmail.com',
    url='https://github.com/sunxianliang/nefertiti',
    packages=find_packages(),
    classifiers=['Development Status :: 3 - Alpha',
                 'Programming Language :: Python',
                 'Programming Language :: Python :: 3.6',
                 'Programming Language :: Python :: 3.7',
                 'Programming Language :: Python :: 3.8',
                 'Programming Language :: Python :: 3.9',
                 # 'Operating System :: MacOS',
                 # 'Operating System :: Microsoft :: Windows',
                 # 'Operating System :: POSIX :: Linux',
                 ],
    install_requires=[],
    extras_require=['Cython',
                    'pytz',
                    'python-dateutil',
                    'lxml',
                    'openpyxl',
                    'xlrd',
                    'XlsxWriter',
                    'pymssql<3.0',
                    'psycopg2',
                    'wheel',
                    'mysqlclient',
                    ]
)
